# Generated by Django 4.0.1 on 2022-01-18 04:30

from django.db import migrations, models
import model_forms.demo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pages', models.IntegerField(validators=[model_forms.demo.models.min_value_validator])),
                ('description', models.CharField(default='', max_length=100)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
